package litskitchenware;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MERYLL MEDINA
 */
public class StaffLogin extends javax.swing.JFrame {

    /**
     * Creates new form StaffLogin
     */
    public StaffLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        UserTF = new javax.swing.JTextField();
        PasswordTF = new javax.swing.JPasswordField();
        Viewbox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        LoginButt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SignupButt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 120, 430, 210));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/441477846_1158283951980106_2400353697483071379_n.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 480));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTFActionPerformed(evt);
            }
        });
        jPanel2.add(UserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 270, -1));
        jPanel2.add(PasswordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 270, -1));

        Viewbox.setText("Show Password");
        Viewbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewboxActionPerformed(evt);
            }
        });
        jPanel2.add(Viewbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 119, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("LIT'S");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 90, -1));

        LoginButt.setBackground(new java.awt.Color(255, 153, 0));
        LoginButt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginButt.setForeground(new java.awt.Color(255, 255, 255));
        LoginButt.setText("Login");
        LoginButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtActionPerformed(evt);
            }
        });
        jPanel2.add(LoginButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 230, 40));

        jLabel3.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        jLabel3.setText("Kitchenware");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 250, 40));

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel5.setText("Username:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel6.setText("Password:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 70, -1));

        SignupButt.setBackground(new java.awt.Color(102, 102, 102));
        SignupButt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SignupButt.setForeground(new java.awt.Color(255, 255, 255));
        SignupButt.setText("Sign up");
        SignupButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtActionPerformed(evt);
            }
        });
        jPanel2.add(SignupButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 190, 40));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("---------- or ----------");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel8.setText("STAFF LOGIN");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 0, 370, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserTFActionPerformed

    private void ViewboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewboxActionPerformed
        // TODO add your handling code here:
         if (Viewbox.isSelected()) {
                    PasswordTF.setEchoChar((char)0);
                } else {
                    PasswordTF.setEchoChar('\u2022'); 
                }
    }//GEN-LAST:event_ViewboxActionPerformed

    private void LoginButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtActionPerformed
        // TODO add your handling code here:
           String url = "jdbc:mysql://localhost:3306/lits";
    String username = "root";
    String password = "";

    String user = UserTF.getText();
    String pass = new String(PasswordTF.getPassword());

    try {
        Connection connection = DriverManager.getConnection(url, username, password);
        String sql = "SELECT * FROM Staff WHERE username = ? AND password = ?";
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setString(1, user);
        statement.setString(2, pass);
        ResultSet resultSet = statement.executeQuery();

        if (resultSet.next()) {
            JOptionPane.showMessageDialog(this, "Login successful");
            NewTransaction NewTransaction = new NewTransaction();
            NewTransaction.setVisible(true);
            dispose(); 
        } else {
            JOptionPane.showMessageDialog(this, "Invalid username or password");
        }

        resultSet.close();
        statement.close();
        connection.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Database connection error");
        e.printStackTrace();
    }
    }//GEN-LAST:event_LoginButtActionPerformed

    private void SignupButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_SignupButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButt;
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JButton SignupButt;
    private javax.swing.JTextField UserTF;
    private javax.swing.JCheckBox Viewbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
